### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by leao-nardo** [omrkcmn/AmazfitVergeRecorder#1]
i tested in verge . does not work even in the IDE android studio with the emulator wear OS android 8.
it instals, loads , ask for permission , but when click rec it stops /gives error

**Comment by omrkcmn** [comment]
Uninstall app and create "Records" folder manually in the main directory. 

The app does not work on emulator.

**Comment by leao-nardo** [comment]
so i tested this first in the emulator but didnt work as u said.

then i made the folder on the watch (a Verge -regular not the lite) and reinstalled the app and it works now it records.

i just saw that is records in .3gp and the watch can not run it but i sended to phone and checked it recorded correctly.

can i change  tha data type to save in mp3 ? how ?
