### ISSUE TITLE
it records in .3gp  can i change to mp3

### ISSUE THREAD

**Issue by leao-nardo** [omrkcmn/AmazfitVergeRecorder#2]
like i said in #1
i just saw that is records in .3gp and the watch can not run it but i sended to phone and checked it recorded correctly.

can i change tha data type to save in mp3  or other format ? how ?

**Comment by omrkcmn** [comment]
> like i said in #1
> i just saw that is records in .3gp and the watch can not run it but i sended to phone and checked it recorded correctly.
> 
> can i change tha data type to save in mp3 or other format ? how ?

Go to MainActivity lines 61 and  80. 

It might work if you change this lines.

`mFileName += "/Records/" + FileName +".3gp";`

mRecord.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
`mRecord.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);`


`+ ".3gp"  => +".mp3"`

`THREE_GPP => MPEG_4 or whatever.`
`AMR_NB => AAC or whatever`

You can check this link: https://developer.android.com/reference/android/media/MediaRecorder.OutputFormat
and this: https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder
